try
{
    int num = 0;
    Console.WriteLine(10/num);
}
catch (Exception ex)
{
    
    Console.WriteLine("Error : " + ex.Message); 
}
